controller_list:
  - name: fake_arm_controller
    joints:
      - virtual_joint
      - base_to_motor1
      - swivel_to_motor2
      - extension
      - wrist_motor_to_extension
  - name: fake_gripper_controller
    joints:
      - finger1_to_gripper_motor