joint:
  names: [gripper]
motion:
  names: [gripper_motion]
  gripper_motion:
    step: [1]
    time_from_start: 2.0



# joint:
#   names: [wrist_tilt, gripper]
# motion:
#   names: [wrist_motion, gripper_motion]
#   wrist_motion:
#     step: [1,1]
#     time_from_start: 2.0  # sec
#   gripper_motion:
#     step: [1,1]
#     time_from_start: 2.0



# joint:
#   names: [base_swivel, vertical_tilt, arm_extension, wrist, wrist_tilt, gripper]
# motion:
#   names: [motion_x, motion_y]
#   motion_x:
#     step: [3.14,3.14,3.14,0,0,0]
#     time_from_start: 2.0  # sec
#   motion_y:
#     step: [3.14,3.14,3.14,1.57,1.57]
#     time_from_start: 3.0