wrta/gazebo_ros_control:
  pid_gains: 
    horizontal_panning: {p: 100.0, i: 0.01, d: 10.0}
    vertical_pitching: {p: 100.0, i: 0.01, d: 10.0}
    length_extension: {p: 100.0, i: 0.01, d: 10.0}
    wrist_rotation: {p: 100.0, i: 0.01, d: 10.0}
    wrist_pitching: {p: 100.0, i: 0.01, d: 10.0}
wrta:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  horizontal_panning_controller:
    type: position_controllers/JointPositionController
    joint: horizontal_panning
  vertical_pitching_controller:
    type: position_controllers/JointPositionController
    joint: vertical_pitching
  length_extension_controller:
    type: position_controllers/JointPositionController
    joint: length_extension
  wrist_rotation_controller:
    type: position_controllers/JointPositionController
    joint: wrist_rotation
  wrist_pitching_controller:
    type: position_controllers/JointPositionController
    joint: wrist_pitching
